### ISSUE TITLE
TypeError: report.map is not a function

### ISSUE THREAD

**Issue by mikaoelitiana** [s0/libyear-node-action#9]
We recently migrated a project package manager from `npm` to `yarn`. We also update our action workflow as follow : 

```
jobs:
  libyear:
    runs-on: ubuntu-latest
    env:
      YARN_NODE_LINKER: node-modules
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v3
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        node-version: 16.14.0
        cache: 'yarn'
    - run: yarn install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Calculate libyear
    - id: libyear
      uses: s0/libyear-node-action@v0.1.2
```

The following error occurs on the libyear step:

```
##[debug]Evaluating condition for step: 'Run s0/libyear-node-action@v0.1.2'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run s0/libyear-node-action@v0.1.2
##[debug]Loading inputs
##[debug]Loading env
Run s0/libyear-node-action@v0.1.2
Result: 
TypeError: Cannot read property 'toFixed' of null
    at /home/runner/work/_actions/s0/libyear-node-action/v0.1.2/dist/main/index.js:3937:26
    at Array.map (<anonymous>)
    at Object.getResultsTable (/home/runner/work/_actions/s0/libyear-node-action/v0.1.2/dist/main/index.js:3933:[19](https://github.com/busbud/public-website/actions/runs/3126873968/jobs/5072933976#step:5:19))
    at /home/runner/work/_actions/s0/libyear-node-action/v0.1.2/dist/main/index.js:4062:41
    at step (/home/runner/work/_actions/s0/libyear-node-action/v0.1.2/dist/main/index.js:4029:23)
    at Object.next (/home/runner/work/_actions/s0/libyear-node-action/v0.1.2/dist/main/index.js:4010:53)
    at fulfilled (/home/runner/work/_actions/s0/libyear-node-action/v0.1.2/dist/main/index.js:4001:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mikaoelitiana** [comment]
My bad, I found what the issue came from. I did not pass the `NPM_TOKEN` environment variable for the libyear action step. 
Now the workflow looks like this: 

```
jobs:
  libyear:
    runs-on: ubuntu-latest
    env:
      YARN_NODE_LINKER: node-modules
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.0
        cache: 'yarn'
    - run: yarn install

    # Calculate libyear
    - id: libyear
      uses: s0/libyear-node-action@v0.1.2

```
